site_name: Edital 23/2024-DG-PAR

theme: material
language: pt


nav:
  - index.md
  - da-natureza-e-finalidades.md
  - dos-objetivos.md
  - requesitos.md
  - atribuicoes.md
  - inscricoes.md
  - vagas.md
  - processo-seletivo.md
  - das-disposicoes-gerais.md
